GRAD_COLOR_DICT = {"Buy": "#128305",
                   "Positive": "#128305",
                   "Long-Term Buy": "#0D5B03",
                   "Long-term Buy": "#0D5B03",
                   "Strong Buy": "#0FFF00",
                   "Overweight": "#4BA207",
                   "Underweight": "#F28F75",
                   "Perform": "#B2B2B2",
                   "Neutral": "#DDE919",
                   "Hold": "#929B0D",
                   "Sector Perform": "#565B08",
                   "Equal-Weight": "#565B08",
                   "Equal-weight": "#565B08",
                   "": "#FFFFFF",
                   "Market Perform": "#858C00",
                   "Sell": "#FF0000",
                   "Negative": "#FF0000",
                   "Outperform": "#4BA207",
                   "Market Outperform": "#4BA207",
                   "Sector Outperform": "#4BA207",
                   "Underperform": "#F28F75"}